name: Build firmware
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: build firmware
      uses: espressif/esp-idf-ci-action@latest
      with:
        path: 'firmware'